"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = void 0;

var _util = require("../core/util");

/**
 * @file santd Table 表格组件 td 模板
 * @author mayihui@baidu.com
 **/
var prefixCls = (0, _util.classCreator)('table')();
var contentTemplate = "\n    <!--\u914D\u7F6E\u5C55\u5F00\u56FE\u6807-->\n    <template s-if=\"isTree && columnIndex === 0\">\n        <span class=\"".concat(prefixCls, "-row-indent indent-level-{{item.level}}\" style=\"padding-left: {{item.level * indentSize}}px;\"></span>\n        <span on-click=\"handleTreeExpand(item)\" s-if=\"hasExpandIcon && item.collapsed !== undefined\">\n            <slot name=\"expandIcon\" var-record=\"{{item}}\"/>\n        </span>\n        <span\n            s-else\n            class=\"").concat(prefixCls, "-row-expand-icon ").concat(prefixCls, "-row-{{item.collapsed !== undefined ? item.collapsed ? 'collapsed' : 'expanded' : 'spaced'}}\"\n            on-click=\"handleTreeExpand(item)\"\n        ></span>\n    </template>\n    <!--\u914D\u7F6Escoped slot-->\n    <slot\n        s-if=\"column.scopedSlots.render && !column.children\"\n        name=\"{{column.scopedSlots.render}}\"\n        var-text=\"{{column.scopedSlots.render === 'render' ? item[column.dataIndex] : item[column.scopedSlots.render]}}\"\n        var-record=\"{{item}}\"\n        var-index=\"{{index}}\"\n        var-column=\"{{column}}\"\n    />\n    <template s-else>{{column.children || item[column.dataIndex] | raw}}</template>\n");
var _default = {
  template: "\n        <td s-if=\"rowSelection\" class=\"".concat(prefixCls, "-selection-column\">\n            <s-checkbox\n                autoFocus=\"{{getCheckboxProps(item, 'autoFocus')}}\"\n                checked=\"{{getItemChecked(item, selectedRowKeys)}}\"\n                defaultChecked=\"{{getCheckboxProps(item, 'defaultChecked')}}\"\n                name=\"{{getCheckboxProps(item, 'name')}}\"\n                disabled=\"{{getCheckboxProps(item, 'disabled')}}\"\n                on-change=\"handleSelection($event, item, index)\"\n            />\n        </td>\n        <template s-for=\"column, columnIndex in getColumns(tdColumns, item, index)\">\n            <td s-if=\"hasExpandedRowRender && columnIndex === 0\" class=\"").concat(prefixCls, "-row-expand-icon-cell\">\n                <span on-click=\"handleExpandRow(item)\" s-if=\"hasExpandIcon\">\n                    <slot name=\"expandIcon\" var-record=\"{{item}}\"/>\n                </span>\n                <span class=\"").concat(prefixCls, "-row-expand-icon ").concat(prefixCls, "-row-{{item.expanded ? 'expanded' : 'collapsed'}}\" on-click=\"handleExpandRow(item)\" s-else></span>\n            </td>\n            <td s-if=\"column.attrs.colSpan\" colspan=\"{{column.attrs.colSpan}}\" class=\"{{getThClass(column)}}\" style=\"{{getThStyle(column)}}\">").concat(contentTemplate, "</td>\n            <td s-else-if=\"column.attrs.rowSpan\" rowspan=\"{{column.attrs.rowSpan}}\" class=\"{{getThClass(column)}}\" style=\"{{getThStyle(column)}}\">").concat(contentTemplate, "</td>\n            <td\n                s-else-if=\"column.attrs.colSpan && column.attrs.rowSpan\"\n                colspan=\"{{column.attrs.colSpan}}\"\n                rowspan=\"{{column.attrs.rowSpan}}\"\n                class=\"{{getThClass(column)}}\"\n                style=\"{{getThStyle(column)}}\"\n            >").concat(contentTemplate, "</td>\n            <td s-else class=\"{{getThClass(column)}}\" style=\"{{getThStyle(column)}}\">").concat(contentTemplate, "</td>\n        </template>\n    ")
};
exports["default"] = _default;